//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssociationTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AssociationTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Professional"/&gt;
 *     &lt;enumeration value="Social"/&gt;
 *     &lt;enumeration value="Community"/&gt;
 *     &lt;enumeration value="Non-Profit"/&gt;
 *     &lt;enumeration value="Religious"/&gt;
 *     &lt;enumeration value="Political"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AssociationTypeType")
@XmlEnum
public enum AssociationTypeType {

    @XmlEnumValue("Professional")
    PROFESSIONAL("Professional"),
    @XmlEnumValue("Social")
    SOCIAL("Social"),
    @XmlEnumValue("Community")
    COMMUNITY("Community"),
    @XmlEnumValue("Non-Profit")
    NON_PROFIT("Non-Profit"),
    @XmlEnumValue("Religious")
    RELIGIOUS("Religious"),
    @XmlEnumValue("Political")
    POLITICAL("Political");
    private final String value;

    AssociationTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AssociationTypeType fromValue(String v) {
        for (AssociationTypeType c: AssociationTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
