//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for CompetencyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompetencyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CompetencyId" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attGroup ref="{http://ns.hr-xml.org/2006-02-28}id"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TaxonomyId" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attGroup ref="{http://ns.hr-xml.org/2006-02-28}id"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CompetencyEvidence" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="EvidenceId" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attGroup ref="{http://ns.hr-xml.org/2006-02-28}id"/&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;choice&gt;
 *                     &lt;element ref="{http://ns.hr-xml.org/2006-02-28}NumericValue"/&gt;
 *                     &lt;element ref="{http://ns.hr-xml.org/2006-02-28}StringValue"/&gt;
 *                   &lt;/choice&gt;
 *                   &lt;element ref="{http://ns.hr-xml.org/2006-02-28}SupportingInformation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="dateOfIncident" type="{http://ns.hr-xml.org/2006-02-28}AnyDateTimeType" /&gt;
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="typeDescription" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="expirationDate" type="{http://ns.hr-xml.org/2006-02-28}AnyDateTimeType" /&gt;
 *                 &lt;attribute name="typeId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                 &lt;attribute name="lastUsed" type="{http://ns.hr-xml.org/2006-02-28}AnyDateTimeType" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CompetencyWeight" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;choice&gt;
 *                     &lt;element ref="{http://ns.hr-xml.org/2006-02-28}NumericValue"/&gt;
 *                     &lt;element ref="{http://ns.hr-xml.org/2006-02-28}StringValue"/&gt;
 *                   &lt;/choice&gt;
 *                   &lt;element ref="{http://ns.hr-xml.org/2006-02-28}SupportingInformation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="type" type="{http://ns.hr-xml.org/2006-02-28}ExtendedWeightType" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element ref="{http://ns.hr-xml.org/2006-02-28}Competency" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.hr-xml.org/2006-02-28}UserArea" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompetencyType", propOrder = {
    "competencyId",
    "taxonomyId",
    "competencyEvidence",
    "competencyWeight",
    "competency",
    "userArea"
})
public class CompetencyType {

    @XmlElement(name = "CompetencyId")
    protected CompetencyType.CompetencyId competencyId;
    @XmlElement(name = "TaxonomyId")
    protected List<TaxonomyId> taxonomyId;
    @XmlElement(name = "CompetencyEvidence")
    protected List<CompetencyEvidence> competencyEvidence;
    @XmlElement(name = "CompetencyWeight")
    protected List<CompetencyWeight> competencyWeight;
    @XmlElement(name = "Competency")
    protected List<CompetencyType> competency;
    @XmlElement(name = "UserArea")
    protected UserAreaType userArea;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "required")
    protected Boolean required;

    /**
     * Gets the value of the competencyId property.
     *
     * @return
     *     possible object is
     *     {@link CompetencyType.CompetencyId }
     *
     */
    public CompetencyType.CompetencyId getCompetencyId() {
        return competencyId;
    }

    /**
     * Sets the value of the competencyId property.
     *
     * @param value
     *     allowed object is
     *     {@link CompetencyType.CompetencyId }
     *
     */
    public void setCompetencyId(CompetencyType.CompetencyId value) {
        this.competencyId = value;
    }

    /**
     * Gets the value of the taxonomyId property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxonomyId property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxonomyId().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompetencyType.TaxonomyId }
     *
     *
     */
    public List<TaxonomyId> getTaxonomyId() {
        if (taxonomyId == null) {
            taxonomyId = new ArrayList<TaxonomyId>();
        }
        return this.taxonomyId;
    }

    /**
     * Gets the value of the competencyEvidence property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the competencyEvidence property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompetencyEvidence().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompetencyType.CompetencyEvidence }
     *
     *
     */
    public List<CompetencyEvidence> getCompetencyEvidence() {
        if (competencyEvidence == null) {
            competencyEvidence = new ArrayList<CompetencyEvidence>();
        }
        return this.competencyEvidence;
    }

    /**
     * Gets the value of the competencyWeight property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the competencyWeight property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompetencyWeight().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompetencyType.CompetencyWeight }
     *
     *
     */
    public List<CompetencyWeight> getCompetencyWeight() {
        if (competencyWeight == null) {
            competencyWeight = new ArrayList<CompetencyWeight>();
        }
        return this.competencyWeight;
    }

    /**
     * Gets the value of the competency property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the competency property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompetency().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompetencyType }
     *
     *
     */
    public List<CompetencyType> getCompetency() {
        if (competency == null) {
            competency = new ArrayList<CompetencyType>();
        }
        return this.competency;
    }

    /**
     * Gets the value of the userArea property.
     *
     * @return
     *     possible object is
     *     {@link UserAreaType }
     *
     */
    public UserAreaType getUserArea() {
        return userArea;
    }

    /**
     * Sets the value of the userArea property.
     *
     * @param value
     *     allowed object is
     *     {@link UserAreaType }
     *
     */
    public void setUserArea(UserAreaType value) {
        this.userArea = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the required property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="EvidenceId" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attGroup ref="{http://ns.hr-xml.org/2006-02-28}id"/&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;choice&gt;
     *           &lt;element ref="{http://ns.hr-xml.org/2006-02-28}NumericValue"/&gt;
     *           &lt;element ref="{http://ns.hr-xml.org/2006-02-28}StringValue"/&gt;
     *         &lt;/choice&gt;
     *         &lt;element ref="{http://ns.hr-xml.org/2006-02-28}SupportingInformation" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="dateOfIncident" type="{http://ns.hr-xml.org/2006-02-28}AnyDateTimeType" /&gt;
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="typeDescription" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="expirationDate" type="{http://ns.hr-xml.org/2006-02-28}AnyDateTimeType" /&gt;
     *       &lt;attribute name="typeId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *       &lt;attribute name="lastUsed" type="{http://ns.hr-xml.org/2006-02-28}AnyDateTimeType" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "evidenceId",
        "numericValue",
        "stringValue",
        "supportingInformation"
    })
    public static class CompetencyEvidence {

        @XmlElement(name = "EvidenceId")
        protected CompetencyType.CompetencyEvidence.EvidenceId evidenceId;
        @XmlElement(name = "NumericValue")
        protected NumericValue numericValue;
        @XmlElement(name = "StringValue")
        protected StringValue stringValue;
        @XmlElement(name = "SupportingInformation")
        protected List<String> supportingInformation;
        @XmlAttribute(name = "dateOfIncident")
        protected String dateOfIncident;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "typeDescription")
        protected String typeDescription;
        @XmlAttribute(name = "expirationDate")
        protected String expirationDate;
        @XmlAttribute(name = "typeId")
        protected String typeId;
        @XmlAttribute(name = "required")
        protected Boolean required;
        @XmlAttribute(name = "lastUsed")
        protected String lastUsed;

        /**
         * Gets the value of the evidenceId property.
         *
         * @return
         *     possible object is
         *     {@link CompetencyType.CompetencyEvidence.EvidenceId }
         *
         */
        public CompetencyType.CompetencyEvidence.EvidenceId getEvidenceId() {
            return evidenceId;
        }

        /**
         * Sets the value of the evidenceId property.
         *
         * @param value
         *     allowed object is
         *     {@link CompetencyType.CompetencyEvidence.EvidenceId }
         *
         */
        public void setEvidenceId(CompetencyType.CompetencyEvidence.EvidenceId value) {
            this.evidenceId = value;
        }

        /**
         * Gets the value of the numericValue property.
         * 
         * @return
         *     possible object is
         *     {@link NumericValue }
         *     
         */
        public NumericValue getNumericValue() {
            return numericValue;
        }

        /**
         * Sets the value of the numericValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link NumericValue }
         *     
         */
        public void setNumericValue(NumericValue value) {
            this.numericValue = value;
        }

        /**
         * Gets the value of the stringValue property.
         * 
         * @return
         *     possible object is
         *     {@link StringValue }
         *     
         */
        public StringValue getStringValue() {
            return stringValue;
        }

        /**
         * Sets the value of the stringValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link StringValue }
         *     
         */
        public void setStringValue(StringValue value) {
            this.stringValue = value;
        }

        /**
         * Gets the value of the supportingInformation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supportingInformation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupportingInformation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getSupportingInformation() {
            if (supportingInformation == null) {
                supportingInformation = new ArrayList<String>();
            }
            return this.supportingInformation;
        }

        /**
         * Gets the value of the dateOfIncident property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDateOfIncident() {
            return dateOfIncident;
        }

        /**
         * Sets the value of the dateOfIncident property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDateOfIncident(String value) {
            this.dateOfIncident = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the typeDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypeDescription() {
            return typeDescription;
        }

        /**
         * Sets the value of the typeDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypeDescription(String value) {
            this.typeDescription = value;
        }

        /**
         * Gets the value of the expirationDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExpirationDate() {
            return expirationDate;
        }

        /**
         * Sets the value of the expirationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpirationDate(String value) {
            this.expirationDate = value;
        }

        /**
         * Gets the value of the typeId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypeId() {
            return typeId;
        }

        /**
         * Sets the value of the typeId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypeId(String value) {
            this.typeId = value;
        }

        /**
         * Gets the value of the required property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isRequired() {
            return required;
        }

        /**
         * Sets the value of the required property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setRequired(Boolean value) {
            this.required = value;
        }

        /**
         * Gets the value of the lastUsed property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastUsed() {
            return lastUsed;
        }

        /**
         * Sets the value of the lastUsed property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastUsed(String value) {
            this.lastUsed = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attGroup ref="{http://ns.hr-xml.org/2006-02-28}id"/&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class EvidenceId {

            @XmlAttribute(name = "id", required = true)
            protected String id;
            @XmlAttribute(name = "idOwner")
            protected String idOwner;
            @XmlAttribute(name = "description")
            protected String description;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the idOwner property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdOwner() {
                return idOwner;
            }

            /**
             * Sets the value of the idOwner property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdOwner(String value) {
                this.idOwner = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attGroup ref="{http://ns.hr-xml.org/2006-02-28}id"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CompetencyId {

        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "idOwner")
        protected String idOwner;
        @XmlAttribute(name = "description")
        protected String description;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the idOwner property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdOwner() {
            return idOwner;
        }

        /**
         * Sets the value of the idOwner property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdOwner(String value) {
            this.idOwner = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;choice&gt;
     *           &lt;element ref="{http://ns.hr-xml.org/2006-02-28}NumericValue"/&gt;
     *           &lt;element ref="{http://ns.hr-xml.org/2006-02-28}StringValue"/&gt;
     *         &lt;/choice&gt;
     *         &lt;element ref="{http://ns.hr-xml.org/2006-02-28}SupportingInformation" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="type" type="{http://ns.hr-xml.org/2006-02-28}ExtendedWeightType" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "numericValue",
        "stringValue",
        "supportingInformation"
    })
    public static class CompetencyWeight {

        @XmlElement(name = "NumericValue")
        protected NumericValue numericValue;
        @XmlElement(name = "StringValue")
        protected StringValue stringValue;
        @XmlElement(name = "SupportingInformation")
        protected List<String> supportingInformation;
        @XmlAttribute(name = "type")
        protected String type;

        /**
         * Gets the value of the numericValue property.
         * 
         * @return
         *     possible object is
         *     {@link NumericValue }
         *     
         */
        public NumericValue getNumericValue() {
            return numericValue;
        }

        /**
         * Sets the value of the numericValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link NumericValue }
         *     
         */
        public void setNumericValue(NumericValue value) {
            this.numericValue = value;
        }

        /**
         * Gets the value of the stringValue property.
         * 
         * @return
         *     possible object is
         *     {@link StringValue }
         *     
         */
        public StringValue getStringValue() {
            return stringValue;
        }

        /**
         * Sets the value of the stringValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link StringValue }
         *     
         */
        public void setStringValue(StringValue value) {
            this.stringValue = value;
        }

        /**
         * Gets the value of the supportingInformation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supportingInformation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupportingInformation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getSupportingInformation() {
            if (supportingInformation == null) {
                supportingInformation = new ArrayList<String>();
            }
            return this.supportingInformation;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attGroup ref="{http://ns.hr-xml.org/2006-02-28}id"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class TaxonomyId {

        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "idOwner")
        protected String idOwner;
        @XmlAttribute(name = "description")
        protected String description;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the idOwner property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdOwner() {
            return idOwner;
        }

        /**
         * Sets the value of the idOwner property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdOwner(String value) {
            this.idOwner = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

    }

}
