//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for DatesOfAttendanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatesOfAttendanceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="StartDate" type="{http://ns.hr-xml.org/2006-02-28}FlexibleDatesType"/&gt;
 *         &lt;element name="EndDate" type="{http://ns.hr-xml.org/2006-02-28}FlexibleDatesType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="enrollmentStatus" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="currentlyEnrolled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="studentInGoodStanding" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatesOfAttendanceType", propOrder = {
    "startDate",
    "endDate"
})
public class DatesOfAttendanceType {

    @XmlElement(name = "StartDate", required = true)
    protected FlexibleDatesType startDate;
    @XmlElement(name = "EndDate")
    protected FlexibleDatesType endDate;
    @XmlAttribute(name = "enrollmentStatus")
    protected String enrollmentStatus;
    @XmlAttribute(name = "currentlyEnrolled")
    protected Boolean currentlyEnrolled;
    @XmlAttribute(name = "studentInGoodStanding")
    protected Boolean studentInGoodStanding;

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link FlexibleDatesType }
     *     
     */
    public FlexibleDatesType getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlexibleDatesType }
     *     
     */
    public void setStartDate(FlexibleDatesType value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link FlexibleDatesType }
     *     
     */
    public FlexibleDatesType getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlexibleDatesType }
     *     
     */
    public void setEndDate(FlexibleDatesType value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the enrollmentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrollmentStatus() {
        return enrollmentStatus;
    }

    /**
     * Sets the value of the enrollmentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrollmentStatus(String value) {
        this.enrollmentStatus = value;
    }

    /**
     * Gets the value of the currentlyEnrolled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCurrentlyEnrolled() {
        return currentlyEnrolled;
    }

    /**
     * Sets the value of the currentlyEnrolled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCurrentlyEnrolled(Boolean value) {
        this.currentlyEnrolled = value;
    }

    /**
     * Gets the value of the studentInGoodStanding property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStudentInGoodStanding() {
        return studentInGoodStanding;
    }

    /**
     * Sets the value of the studentInGoodStanding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStudentInGoodStanding(Boolean value) {
        this.studentInGoodStanding = value;
    }

}
