//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for degreeCodeTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="degreeCodeTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="B17"/&gt;
 *     &lt;enumeration value="B18"/&gt;
 *     &lt;enumeration value="B19"/&gt;
 *     &lt;enumeration value="B20"/&gt;
 *     &lt;enumeration value="B21"/&gt;
 *     &lt;enumeration value="B22"/&gt;
 *     &lt;enumeration value="B23"/&gt;
 *     &lt;enumeration value="B24"/&gt;
 *     &lt;enumeration value="B25"/&gt;
 *     &lt;enumeration value="B26"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "degreeCodeTypes")
@XmlEnum
public enum DegreeCodeTypes {


    /**
     * Did not complete secondary school
     * 
     */
    @XmlEnumValue("B17")
    B_17("B17"),

    /**
     * Standard high school diploma
     * 
     */
    @XmlEnumValue("B18")
    B_18("B18"),

    /**
     * Advanced or honors diploma
     * 
     */
    @XmlEnumValue("B19")
    B_19("B19"),

    /**
     * Vocational diploma
     * 
     */
    @XmlEnumValue("B20")
    B_20("B20"),

    /**
     * Special education diploma
     * 
     */
    @XmlEnumValue("B21")
    B_21("B21"),

    /**
     * Certificate of completion or attendance
     * 
     */
    @XmlEnumValue("B22")
    B_22("B22"),

    /**
     * Special certificate of completion
     * 
     */
    @XmlEnumValue("B23")
    B_23("B23"),

    /**
     * General Education Development Diploma (GED)
     * 
     */
    @XmlEnumValue("B24")
    B_24("B24"),

    /**
     * Other high school equivalency diploma
     * 
     */
    @XmlEnumValue("B25")
    B_25("B25"),

    /**
     * International diploma or certificate (such as International Baccalaureate)
     * 
     */
    @XmlEnumValue("B26")
    B_26("B26");
    private final String value;

    DegreeCodeTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DegreeCodeTypes fromValue(String v) {
        for (DegreeCodeTypes c: DegreeCodeTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
