//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * This type is the same as the DatesOfAttendanceType, except it is an unbounded sequence.  This remains for backward compatibility only.  
 * 
 * <p>Java class for DeprecatedDatesOfAttendanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeprecatedDatesOfAttendanceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded"&gt;
 *         &lt;element name="StartDate" type="{http://ns.hr-xml.org/2006-02-28}FlexibleDatesType"/&gt;
 *         &lt;element name="EndDate" type="{http://ns.hr-xml.org/2006-02-28}FlexibleDatesType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="enrollmentStatus" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="currentlyEnrolled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="studentInGoodStanding" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeprecatedDatesOfAttendanceType", propOrder = {
    "startDateAndEndDate"
})
public class DeprecatedDatesOfAttendanceType {

    @XmlElementRefs({
        @XmlElementRef(name = "StartDate", namespace = "http://ns.hr-xml.org/2006-02-28", type = JAXBElement.class),
        @XmlElementRef(name = "EndDate", namespace = "http://ns.hr-xml.org/2006-02-28", type = JAXBElement.class)
    })
    protected List<JAXBElement<FlexibleDatesType>> startDateAndEndDate;
    @XmlAttribute(name = "enrollmentStatus")
    protected String enrollmentStatus;
    @XmlAttribute(name = "currentlyEnrolled")
    protected Boolean currentlyEnrolled;
    @XmlAttribute(name = "studentInGoodStanding")
    protected Boolean studentInGoodStanding;

    /**
     * Gets the value of the startDateAndEndDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the startDateAndEndDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStartDateAndEndDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link FlexibleDatesType }{@code >}
     * {@link JAXBElement }{@code <}{@link FlexibleDatesType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<FlexibleDatesType>> getStartDateAndEndDate() {
        if (startDateAndEndDate == null) {
            startDateAndEndDate = new ArrayList<JAXBElement<FlexibleDatesType>>();
        }
        return this.startDateAndEndDate;
    }

    /**
     * Gets the value of the enrollmentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrollmentStatus() {
        return enrollmentStatus;
    }

    /**
     * Sets the value of the enrollmentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrollmentStatus(String value) {
        this.enrollmentStatus = value;
    }

    /**
     * Gets the value of the currentlyEnrolled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCurrentlyEnrolled() {
        return currentlyEnrolled;
    }

    /**
     * Sets the value of the currentlyEnrolled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCurrentlyEnrolled(Boolean value) {
        this.currentlyEnrolled = value;
    }

    /**
     * Gets the value of the studentInGoodStanding property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStudentInGoodStanding() {
        return studentInGoodStanding;
    }

    /**
     * Sets the value of the studentInGoodStanding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStudentInGoodStanding(Boolean value) {
        this.studentInGoodStanding = value;
    }

}
