//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for DunsNumberDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DunsNumberDataType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://ns.hr-xml.org/2006-02-28&gt;DunsNumberBaseType"&gt;
 *       &lt;attribute name="dunsNumberType" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="standard Duns"/&gt;
 *             &lt;enumeration value="global ultimate"/&gt;
 *             &lt;enumeration value="domestic ultimate"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DunsNumberDataType", propOrder = {
    "value"
})
public class DunsNumberDataType {

    @XmlValue
    protected BigInteger value;
    @XmlAttribute(name = "dunsNumberType", required = true)
    protected String dunsNumberType;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setValue(BigInteger value) {
        this.value = value;
    }

    /**
     * Gets the value of the dunsNumberType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDunsNumberType() {
        return dunsNumberType;
    }

    /**
     * Sets the value of the dunsNumberType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDunsNumberType(String value) {
        this.dunsNumberType = value;
    }

}
