//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import com.sovren.hr_xml._2006_02_28.DegreeUserArea;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for EduDegreeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EduDegreeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DegreeName" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="academicHonors" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="honorsProgram" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DegreeDate" type="{http://ns.hr-xml.org/2006-02-28}FlexibleDatesType" minOccurs="0"/&gt;
 *         &lt;element name="OtherHonors" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DegreeMajor" type="{http://ns.hr-xml.org/2006-02-28}MajorType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="DegreeMinor" type="{http://ns.hr-xml.org/2006-02-28}MinorType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="DegreeMeasure" type="{http://ns.hr-xml.org/2006-02-28}EducationalMeasureType" minOccurs="0"/&gt;
 *         &lt;element name="DatesOfAttendance" type="{http://ns.hr-xml.org/2006-02-28}DatesOfAttendanceType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UserArea" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                   &lt;element ref="{http://sovren.com/hr-xml/2006-02-28}DegreeUserArea" minOccurs="0"/&gt;
 *                 &lt;/all&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="degreeType" type="{http://ns.hr-xml.org/2006-02-28}DegreeTypeStringExtensionType" /&gt;
 *       &lt;attribute name="examPassed" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="graduatingDegree" type="{http://ns.hr-xml.org/2006-02-28}GraduatingDegreeType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EduDegreeType", propOrder = {
    "degreeName",
    "degreeDate",
    "otherHonors",
    "degreeMajor",
    "degreeMinor",
    "degreeMeasure",
    "datesOfAttendance",
    "comments",
    "userArea"
})
public class EduDegreeType {

    @XmlElement(name = "DegreeName")
    protected EduDegreeType.DegreeName degreeName;
    @XmlElement(name = "DegreeDate")
    protected FlexibleDatesType degreeDate;
    @XmlElement(name = "OtherHonors")
    protected List<OtherHonors> otherHonors;
    @XmlElement(name = "DegreeMajor")
    protected List<MajorType> degreeMajor;
    @XmlElement(name = "DegreeMinor")
    protected List<MinorType> degreeMinor;
    @XmlElement(name = "DegreeMeasure")
    protected EducationalMeasureType degreeMeasure;
    @XmlElement(name = "DatesOfAttendance")
    protected List<DatesOfAttendanceType> datesOfAttendance;
    @XmlElement(name = "Comments")
    protected String comments;
    @XmlElement(name = "UserArea")
    protected EduDegreeType.UserArea userArea;
    @XmlAttribute(name = "degreeType")
    protected String degreeType;
    @XmlAttribute(name = "examPassed")
    protected Boolean examPassed;
    @XmlAttribute(name = "graduatingDegree")
    protected GraduatingDegreeType graduatingDegree;

    /**
     * Gets the value of the degreeName property.
     *
     * @return
     *     possible object is
     *     {@link EduDegreeType.DegreeName }
     *
     */
    public EduDegreeType.DegreeName getDegreeName() {
        return degreeName;
    }

    /**
     * Sets the value of the degreeName property.
     *
     * @param value
     *     allowed object is
     *     {@link EduDegreeType.DegreeName }
     *
     */
    public void setDegreeName(EduDegreeType.DegreeName value) {
        this.degreeName = value;
    }

    /**
     * Gets the value of the degreeDate property.
     *
     * @return
     *     possible object is
     *     {@link FlexibleDatesType }
     *
     */
    public FlexibleDatesType getDegreeDate() {
        return degreeDate;
    }

    /**
     * Sets the value of the degreeDate property.
     *
     * @param value
     *     allowed object is
     *     {@link FlexibleDatesType }
     *
     */
    public void setDegreeDate(FlexibleDatesType value) {
        this.degreeDate = value;
    }

    /**
     * Gets the value of the otherHonors property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherHonors property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherHonors().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EduDegreeType.OtherHonors }
     *
     *
     */
    public List<OtherHonors> getOtherHonors() {
        if (otherHonors == null) {
            otherHonors = new ArrayList<OtherHonors>();
        }
        return this.otherHonors;
    }

    /**
     * Gets the value of the degreeMajor property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the degreeMajor property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDegreeMajor().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MajorType }
     *
     *
     */
    public List<MajorType> getDegreeMajor() {
        if (degreeMajor == null) {
            degreeMajor = new ArrayList<MajorType>();
        }
        return this.degreeMajor;
    }

    /**
     * Gets the value of the degreeMinor property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the degreeMinor property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDegreeMinor().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MinorType }
     *
     *
     */
    public List<MinorType> getDegreeMinor() {
        if (degreeMinor == null) {
            degreeMinor = new ArrayList<MinorType>();
        }
        return this.degreeMinor;
    }

    /**
     * Gets the value of the degreeMeasure property.
     *
     * @return
     *     possible object is
     *     {@link EducationalMeasureType }
     *
     */
    public EducationalMeasureType getDegreeMeasure() {
        return degreeMeasure;
    }

    /**
     * Sets the value of the degreeMeasure property.
     *
     * @param value
     *     allowed object is
     *     {@link EducationalMeasureType }
     *
     */
    public void setDegreeMeasure(EducationalMeasureType value) {
        this.degreeMeasure = value;
    }

    /**
     * Gets the value of the datesOfAttendance property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datesOfAttendance property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatesOfAttendance().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatesOfAttendanceType }
     *
     *
     */
    public List<DatesOfAttendanceType> getDatesOfAttendance() {
        if (datesOfAttendance == null) {
            datesOfAttendance = new ArrayList<DatesOfAttendanceType>();
        }
        return this.datesOfAttendance;
    }

    /**
     * Gets the value of the comments property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the userArea property.
     *
     * @return
     *     possible object is
     *     {@link EduDegreeType.UserArea }
     *
     */
    public EduDegreeType.UserArea getUserArea() {
        return userArea;
    }

    /**
     * Sets the value of the userArea property.
     *
     * @param value
     *     allowed object is
     *     {@link EduDegreeType.UserArea }
     *
     */
    public void setUserArea(EduDegreeType.UserArea value) {
        this.userArea = value;
    }

    /**
     * Gets the value of the degreeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDegreeType() {
        return degreeType;
    }

    /**
     * Sets the value of the degreeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDegreeType(String value) {
        this.degreeType = value;
    }

    /**
     * Gets the value of the examPassed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExamPassed() {
        return examPassed;
    }

    /**
     * Sets the value of the examPassed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExamPassed(Boolean value) {
        this.examPassed = value;
    }

    /**
     * Gets the value of the graduatingDegree property.
     * 
     * @return
     *     possible object is
     *     {@link GraduatingDegreeType }
     *     
     */
    public GraduatingDegreeType getGraduatingDegree() {
        return graduatingDegree;
    }

    /**
     * Sets the value of the graduatingDegree property.
     * 
     * @param value
     *     allowed object is
     *     {@link GraduatingDegreeType }
     *     
     */
    public void setGraduatingDegree(GraduatingDegreeType value) {
        this.graduatingDegree = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="academicHonors" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="honorsProgram" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class DegreeName {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "academicHonors")
        protected String academicHonors;
        @XmlAttribute(name = "honorsProgram")
        protected String honorsProgram;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the academicHonors property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAcademicHonors() {
            return academicHonors;
        }

        /**
         * Sets the value of the academicHonors property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAcademicHonors(String value) {
            this.academicHonors = value;
        }

        /**
         * Gets the value of the honorsProgram property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHonorsProgram() {
            return honorsProgram;
        }

        /**
         * Sets the value of the honorsProgram property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHonorsProgram(String value) {
            this.honorsProgram = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class OtherHonors {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "type")
        protected String type;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *         &lt;element ref="{http://sovren.com/hr-xml/2006-02-28}DegreeUserArea" minOccurs="0"/&gt;
     *       &lt;/all&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class UserArea {

        @XmlElement(name = "DegreeUserArea", namespace = "http://sovren.com/hr-xml/2006-02-28")
        protected DegreeUserArea degreeUserArea;

        /**
         * Gets the value of the degreeUserArea property.
         * 
         * @return
         *     possible object is
         *     {@link DegreeUserArea }
         *     
         */
        public DegreeUserArea getDegreeUserArea() {
            return degreeUserArea;
        }

        /**
         * Sets the value of the degreeUserArea property.
         * 
         * @param value
         *     allowed object is
         *     {@link DegreeUserArea }
         *     
         */
        public void setDegreeUserArea(DegreeUserArea value) {
            this.degreeUserArea = value;
        }

    }

}
