//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for employerOrgTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="employerOrgTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="soleEmployer"/&gt;
 *     &lt;enumeration value="agent"/&gt;
 *     &lt;enumeration value="broker"/&gt;
 *     &lt;enumeration value="self"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "employerOrgTypes")
@XmlEnum
public enum EmployerOrgTypes {

    @XmlEnumValue("soleEmployer")
    SOLE_EMPLOYER("soleEmployer"),
    @XmlEnumValue("agent")
    AGENT("agent"),
    @XmlEnumValue("broker")
    BROKER("broker"),
    @XmlEnumValue("self")
    SELF("self");
    private final String value;

    EmployerOrgTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EmployerOrgTypes fromValue(String v) {
        for (EmployerOrgTypes c: EmployerOrgTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
