//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EventTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="convention"/&gt;
 *     &lt;enumeration value="rally"/&gt;
 *     &lt;enumeration value="conference"/&gt;
 *     &lt;enumeration value="sales meeting"/&gt;
 *     &lt;enumeration value="television show"/&gt;
 *     &lt;enumeration value="radio show"/&gt;
 *     &lt;enumeration value="web-based"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EventTypeType")
@XmlEnum
public enum EventTypeType {

    @XmlEnumValue("convention")
    CONVENTION("convention"),
    @XmlEnumValue("rally")
    RALLY("rally"),
    @XmlEnumValue("conference")
    CONFERENCE("conference"),
    @XmlEnumValue("sales meeting")
    SALES_MEETING("sales meeting"),
    @XmlEnumValue("television show")
    TELEVISION_SHOW("television show"),
    @XmlEnumValue("radio show")
    RADIO_SHOW("radio show"),
    @XmlEnumValue("web-based")
    WEB_BASED("web-based");
    private final String value;

    EventTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EventTypeType fromValue(String v) {
        for (EventTypeType c: EventTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
