//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for intervalTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="intervalTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="hourly"/&gt;
 *     &lt;enumeration value="daily"/&gt;
 *     &lt;enumeration value="weekly"/&gt;
 *     &lt;enumeration value="monthly"/&gt;
 *     &lt;enumeration value="quarterly"/&gt;
 *     &lt;enumeration value="yearly"/&gt;
 *     &lt;enumeration value="semi-monthly"/&gt;
 *     &lt;enumeration value="biweekly"/&gt;
 *     &lt;enumeration value="fortnightly"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "intervalTypes")
@XmlEnum
public enum IntervalTypes {

    @XmlEnumValue("hourly")
    HOURLY("hourly"),
    @XmlEnumValue("daily")
    DAILY("daily"),
    @XmlEnumValue("weekly")
    WEEKLY("weekly"),
    @XmlEnumValue("monthly")
    MONTHLY("monthly"),
    @XmlEnumValue("quarterly")
    QUARTERLY("quarterly"),
    @XmlEnumValue("yearly")
    YEARLY("yearly"),
    @XmlEnumValue("semi-monthly")
    SEMI_MONTHLY("semi-monthly"),
    @XmlEnumValue("biweekly")
    BIWEEKLY("biweekly"),
    @XmlEnumValue("fortnightly")
    FORTNIGHTLY("fortnightly");
    private final String value;

    IntervalTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IntervalTypes fromValue(String v) {
        for (IntervalTypes c: IntervalTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
