//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for MilitaryHistoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MilitaryHistoryType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CountryServed" type="{http://ns.hr-xml.org/2006-02-28}CountryCodeType"/&gt;
 *         &lt;element name="ServiceNumber" type="{http://ns.hr-xml.org/2006-02-28}EntityIdType" minOccurs="0"/&gt;
 *         &lt;element name="ServiceDetail" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="UnitOrDivision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="RankAchieved" type="{http://ns.hr-xml.org/2006-02-28}RankAchievedType" minOccurs="0"/&gt;
 *                   &lt;element name="DatesOfService" type="{http://ns.hr-xml.org/2006-02-28}DatesOfServiceType"/&gt;
 *                   &lt;element name="Campaign" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="AreaOfExpertise" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="RecognitionAchieved" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="DisciplinaryAction" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="DischargeStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element ref="{http://ns.hr-xml.org/2006-02-28}UserArea" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="branch" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ServiceStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://ns.hr-xml.org/2006-02-28}UserArea" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MilitaryHistoryType", propOrder = {
    "countryServed",
    "serviceNumber",
    "serviceDetail",
    "serviceStatus",
    "comments",
    "userArea"
})
public class MilitaryHistoryType {

    @XmlElement(name = "CountryServed", required = true)
    protected String countryServed;
    @XmlElement(name = "ServiceNumber")
    protected EntityIdType serviceNumber;
    @XmlElement(name = "ServiceDetail")
    protected List<ServiceDetail> serviceDetail;
    @XmlElement(name = "ServiceStatus")
    protected String serviceStatus;
    @XmlElement(name = "Comments")
    protected String comments;
    @XmlElement(name = "UserArea")
    protected UserAreaType userArea;

    /**
     * Gets the value of the countryServed property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCountryServed() {
        return countryServed;
    }

    /**
     * Sets the value of the countryServed property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCountryServed(String value) {
        this.countryServed = value;
    }

    /**
     * Gets the value of the serviceNumber property.
     *
     * @return
     *     possible object is
     *     {@link EntityIdType }
     *
     */
    public EntityIdType getServiceNumber() {
        return serviceNumber;
    }

    /**
     * Sets the value of the serviceNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link EntityIdType }
     *
     */
    public void setServiceNumber(EntityIdType value) {
        this.serviceNumber = value;
    }

    /**
     * Gets the value of the serviceDetail property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceDetail property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceDetail().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MilitaryHistoryType.ServiceDetail }
     *
     *
     */
    public List<ServiceDetail> getServiceDetail() {
        if (serviceDetail == null) {
            serviceDetail = new ArrayList<ServiceDetail>();
        }
        return this.serviceDetail;
    }

    /**
     * Gets the value of the serviceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceStatus() {
        return serviceStatus;
    }

    /**
     * Sets the value of the serviceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceStatus(String value) {
        this.serviceStatus = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the userArea property.
     * 
     * @return
     *     possible object is
     *     {@link UserAreaType }
     *     
     */
    public UserAreaType getUserArea() {
        return userArea;
    }

    /**
     * Sets the value of the userArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAreaType }
     *     
     */
    public void setUserArea(UserAreaType value) {
        this.userArea = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="UnitOrDivision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="RankAchieved" type="{http://ns.hr-xml.org/2006-02-28}RankAchievedType" minOccurs="0"/&gt;
     *         &lt;element name="DatesOfService" type="{http://ns.hr-xml.org/2006-02-28}DatesOfServiceType"/&gt;
     *         &lt;element name="Campaign" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="AreaOfExpertise" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="RecognitionAchieved" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="DisciplinaryAction" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="DischargeStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element ref="{http://ns.hr-xml.org/2006-02-28}UserArea" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="branch" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "unitOrDivision",
        "rankAchieved",
        "datesOfService",
        "campaign",
        "areaOfExpertise",
        "recognitionAchieved",
        "disciplinaryAction",
        "dischargeStatus",
        "userArea"
    })
    public static class ServiceDetail {

        @XmlElement(name = "UnitOrDivision")
        protected String unitOrDivision;
        @XmlElement(name = "RankAchieved")
        protected RankAchievedType rankAchieved;
        @XmlElement(name = "DatesOfService", required = true)
        protected DatesOfServiceType datesOfService;
        @XmlElement(name = "Campaign")
        protected List<String> campaign;
        @XmlElement(name = "AreaOfExpertise")
        protected List<String> areaOfExpertise;
        @XmlElement(name = "RecognitionAchieved")
        protected List<String> recognitionAchieved;
        @XmlElement(name = "DisciplinaryAction")
        protected List<String> disciplinaryAction;
        @XmlElement(name = "DischargeStatus")
        protected String dischargeStatus;
        @XmlElement(name = "UserArea")
        protected UserAreaType userArea;
        @XmlAttribute(name = "branch", required = true)
        protected String branch;

        /**
         * Gets the value of the unitOrDivision property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnitOrDivision() {
            return unitOrDivision;
        }

        /**
         * Sets the value of the unitOrDivision property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnitOrDivision(String value) {
            this.unitOrDivision = value;
        }

        /**
         * Gets the value of the rankAchieved property.
         * 
         * @return
         *     possible object is
         *     {@link RankAchievedType }
         *     
         */
        public RankAchievedType getRankAchieved() {
            return rankAchieved;
        }

        /**
         * Sets the value of the rankAchieved property.
         * 
         * @param value
         *     allowed object is
         *     {@link RankAchievedType }
         *     
         */
        public void setRankAchieved(RankAchievedType value) {
            this.rankAchieved = value;
        }

        /**
         * Gets the value of the datesOfService property.
         * 
         * @return
         *     possible object is
         *     {@link DatesOfServiceType }
         *     
         */
        public DatesOfServiceType getDatesOfService() {
            return datesOfService;
        }

        /**
         * Sets the value of the datesOfService property.
         * 
         * @param value
         *     allowed object is
         *     {@link DatesOfServiceType }
         *     
         */
        public void setDatesOfService(DatesOfServiceType value) {
            this.datesOfService = value;
        }

        /**
         * Gets the value of the campaign property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the campaign property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCampaign().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCampaign() {
            if (campaign == null) {
                campaign = new ArrayList<String>();
            }
            return this.campaign;
        }

        /**
         * Gets the value of the areaOfExpertise property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the areaOfExpertise property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAreaOfExpertise().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAreaOfExpertise() {
            if (areaOfExpertise == null) {
                areaOfExpertise = new ArrayList<String>();
            }
            return this.areaOfExpertise;
        }

        /**
         * Gets the value of the recognitionAchieved property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the recognitionAchieved property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRecognitionAchieved().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getRecognitionAchieved() {
            if (recognitionAchieved == null) {
                recognitionAchieved = new ArrayList<String>();
            }
            return this.recognitionAchieved;
        }

        /**
         * Gets the value of the disciplinaryAction property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the disciplinaryAction property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDisciplinaryAction().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getDisciplinaryAction() {
            if (disciplinaryAction == null) {
                disciplinaryAction = new ArrayList<String>();
            }
            return this.disciplinaryAction;
        }

        /**
         * Gets the value of the dischargeStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDischargeStatus() {
            return dischargeStatus;
        }

        /**
         * Sets the value of the dischargeStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDischargeStatus(String value) {
            this.dischargeStatus = value;
        }

        /**
         * Gets the value of the userArea property.
         * 
         * @return
         *     possible object is
         *     {@link UserAreaType }
         *     
         */
        public UserAreaType getUserArea() {
            return userArea;
        }

        /**
         * Sets the value of the userArea property.
         * 
         * @param value
         *     allowed object is
         *     {@link UserAreaType }
         *     
         */
        public void setUserArea(UserAreaType value) {
            this.userArea = value;
        }

        /**
         * Gets the value of the branch property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBranch() {
            return branch;
        }

        /**
         * Sets the value of the branch property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBranch(String value) {
            this.branch = value;
        }

    }

}
