//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for NonXMLResumeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NonXMLResumeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TextResume" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LinkToResume" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SupportingMaterials" type="{http://ns.hr-xml.org/2006-02-28}StaffingSupportingMaterialsType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;group ref="{http://ns.hr-xml.org/2006-02-28}Comments" minOccurs="0"/&gt;
 *         &lt;element name="RevisionDate" type="{http://ns.hr-xml.org/2006-02-28}AnyDateTimeNkType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NonXMLResumeType", propOrder = {
    "textResume",
    "linkToResume",
    "supportingMaterials",
    "comments",
    "revisionDate"
})
public class NonXMLResumeType {

    @XmlElement(name = "TextResume")
    protected String textResume;
    @XmlElement(name = "LinkToResume")
    protected String linkToResume;
    @XmlElement(name = "SupportingMaterials")
    protected List<StaffingSupportingMaterialsType> supportingMaterials;
    @XmlElement(name = "Comments")
    protected String comments;
    @XmlElement(name = "RevisionDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String revisionDate;

    /**
     * Gets the value of the textResume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextResume() {
        return textResume;
    }

    /**
     * Sets the value of the textResume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextResume(String value) {
        this.textResume = value;
    }

    /**
     * Gets the value of the linkToResume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkToResume() {
        return linkToResume;
    }

    /**
     * Sets the value of the linkToResume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkToResume(String value) {
        this.linkToResume = value;
    }

    /**
     * Gets the value of the supportingMaterials property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportingMaterials property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportingMaterials().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StaffingSupportingMaterialsType }
     * 
     * 
     */
    public List<StaffingSupportingMaterialsType> getSupportingMaterials() {
        if (supportingMaterials == null) {
            supportingMaterials = new ArrayList<StaffingSupportingMaterialsType>();
        }
        return this.supportingMaterials;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the revisionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevisionDate() {
        return revisionDate;
    }

    /**
     * Sets the value of the revisionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevisionDate(String value) {
        this.revisionDate = value;
    }

}
