//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import java.math.BigInteger;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ufj.parser.model.sovren package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Achievement_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "Achievement");
    private final static QName _AreaCityCode_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "AreaCityCode");
    private final static QName _Competency_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "Competency");
    private final static QName _CountryCode_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "CountryCode");
    private final static QName _CurrencyCode_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "CurrencyCode");
    private final static QName _DunsNumber_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "DunsNumber");
    private final static QName _EducationHistory_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "EducationHistory");
    private final static QName _EmploymentHistory_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "EmploymentHistory");
    private final static QName _Extension_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "Extension");
    private final static QName _Fax_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "Fax");
    private final static QName _FormattedNumber_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "FormattedNumber");
    private final static QName _GenderCode_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "GenderCode");
    private final static QName _InternationalCountryCode_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "InternationalCountryCode");
    private final static QName _InternetDomainName_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "InternetDomainName");
    private final static QName _InternetEmailAddress_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "InternetEmailAddress");
    private final static QName _InternetWebAddress_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "InternetWebAddress");
    private final static QName _LanguageCode_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "LanguageCode");
    private final static QName _LicenseOrCertification_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "LicenseOrCertification");
    private final static QName _Location_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "Location");
    private final static QName _MilitaryHistory_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "MilitaryHistory");
    private final static QName _Mobile_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "Mobile");
    private final static QName _NationalNumber_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "NationalNumber");
    private final static QName _NonXMLResume_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "NonXMLResume");
    private final static QName _Pager_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "Pager");
    private final static QName _PatentHistory_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "PatentHistory");
    private final static QName _PersonName_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "PersonName");
    private final static QName _PostalAddress_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "PostalAddress");
    private final static QName _PublicationHistory_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "PublicationHistory");
    private final static QName _Reference_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "Reference");
    private final static QName _StructuredXMLResume_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "StructuredXMLResume");
    private final static QName _ResumeAdditionalItem_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "ResumeAdditionalItem");
    private final static QName _SecurityCredential_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "SecurityCredential");
    private final static QName _SpeakingEvent_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "SpeakingEvent");
    private final static QName _SubscriberNumber_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "SubscriberNumber");
    private final static QName _SupportingInformation_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "SupportingInformation");
    private final static QName _Telephone_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "Telephone");
    private final static QName _TTYTDD_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "TTYTDD");
    private final static QName _Use_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "Use");
    private final static QName _UserArea_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "UserArea");
    private final static QName _WhenAvailable_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "WhenAvailable");
    private final static QName _DeprecatedDatesOfAttendanceTypeStartDate_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "StartDate");
    private final static QName _DeprecatedDatesOfAttendanceTypeEndDate_QNAME = new QName("http://ns.hr-xml.org/2006-02-28", "EndDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ufj.parser.model.sovren
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AssociationType }
     * 
     */
    public AssociationType createAssociationType() {
        return new AssociationType();
    }

    /**
     * Create an instance of {@link Resume }
     * 
     */
    public Resume createResume() {
        return new Resume();
    }

    /**
     * Create an instance of {@link VerificationType }
     * 
     */
    public VerificationType createVerificationType() {
        return new VerificationType();
    }

    /**
     * Create an instance of {@link StaffingSupportingMaterialsType }
     * 
     */
    public StaffingSupportingMaterialsType createStaffingSupportingMaterialsType() {
        return new StaffingSupportingMaterialsType();
    }

    /**
     * Create an instance of {@link SchoolOrInstitutionType }
     * 
     */
    public SchoolOrInstitutionType createSchoolOrInstitutionType() {
        return new SchoolOrInstitutionType();
    }

    /**
     * Create an instance of {@link RatingType }
     * 
     */
    public RatingType createRatingType() {
        return new RatingType();
    }

    /**
     * Create an instance of {@link PositionOrgIndustryType }
     * 
     */
    public PositionOrgIndustryType createPositionOrgIndustryType() {
        return new PositionOrgIndustryType();
    }

    /**
     * Create an instance of {@link PositionHistoryType }
     * 
     */
    public PositionHistoryType createPositionHistoryType() {
        return new PositionHistoryType();
    }

    /**
     * Create an instance of {@link PositionCompensationType }
     * 
     */
    public PositionCompensationType createPositionCompensationType() {
        return new PositionCompensationType();
    }

    /**
     * Create an instance of {@link PatentDescriptionType }
     * 
     */
    public PatentDescriptionType createPatentDescriptionType() {
        return new PatentDescriptionType();
    }

    /**
     * Create an instance of {@link PatentDescriptionType.PatentDetail }
     * 
     */
    public PatentDescriptionType.PatentDetail createPatentDescriptionTypePatentDetail() {
        return new PatentDescriptionType.PatentDetail();
    }

    /**
     * Create an instance of {@link BasicBibliographicRecordType }
     * 
     */
    public BasicBibliographicRecordType createBasicBibliographicRecordType() {
        return new BasicBibliographicRecordType();
    }

    /**
     * Create an instance of {@link PersonNameType }
     * 
     */
    public PersonNameType createPersonNameType() {
        return new PersonNameType();
    }

    /**
     * Create an instance of {@link PersonNameType.AlternateScript }
     * 
     */
    public PersonNameType.AlternateScript createPersonNameTypeAlternateScript() {
        return new PersonNameType.AlternateScript();
    }

    /**
     * Create an instance of {@link OccupationalCategoryType }
     * 
     */
    public OccupationalCategoryType createOccupationalCategoryType() {
        return new OccupationalCategoryType();
    }

    /**
     * Create an instance of {@link EmployerOrgDataType }
     * 
     */
    public EmployerOrgDataType createEmployerOrgDataType() {
        return new EmployerOrgDataType();
    }

    /**
     * Create an instance of {@link EduDegreeType }
     * 
     */
    public EduDegreeType createEduDegreeType() {
        return new EduDegreeType();
    }

    /**
     * Create an instance of {@link EducationalMeasureType }
     * 
     */
    public EducationalMeasureType createEducationalMeasureType() {
        return new EducationalMeasureType();
    }

    /**
     * Create an instance of {@link CopyrightType }
     * 
     */
    public CopyrightType createCopyrightType() {
        return new CopyrightType();
    }

    /**
     * Create an instance of {@link AdditionalItemType }
     * 
     */
    public AdditionalItemType createAdditionalItemType() {
        return new AdditionalItemType();
    }

    /**
     * Create an instance of {@link StructuredXMLResumeType }
     * 
     */
    public StructuredXMLResumeType createStructuredXMLResumeType() {
        return new StructuredXMLResumeType();
    }

    /**
     * Create an instance of {@link DistributionGuidelinesType }
     * 
     */
    public DistributionGuidelinesType createDistributionGuidelinesType() {
        return new DistributionGuidelinesType();
    }

    /**
     * Create an instance of {@link PublicationHistoryType }
     * 
     */
    public PublicationHistoryType createPublicationHistoryType() {
        return new PublicationHistoryType();
    }

    /**
     * Create an instance of {@link PostalAddressType }
     * 
     */
    public PostalAddressType createPostalAddressType() {
        return new PostalAddressType();
    }

    /**
     * Create an instance of {@link MilitaryHistoryType }
     * 
     */
    public MilitaryHistoryType createMilitaryHistoryType() {
        return new MilitaryHistoryType();
    }

    /**
     * Create an instance of {@link CredentialType }
     * 
     */
    public CredentialType createCredentialType() {
        return new CredentialType();
    }

    /**
     * Create an instance of {@link CompetencyType }
     * 
     */
    public CompetencyType createCompetencyType() {
        return new CompetencyType();
    }

    /**
     * Create an instance of {@link CompetencyType.CompetencyEvidence }
     * 
     */
    public CompetencyType.CompetencyEvidence createCompetencyTypeCompetencyEvidence() {
        return new CompetencyType.CompetencyEvidence();
    }

    /**
     * Create an instance of {@link EntityIdType }
     * 
     */
    public EntityIdType createEntityIdType() {
        return new EntityIdType();
    }

    /**
     * Create an instance of {@link AchievementType }
     * 
     */
    public AchievementType createAchievementType() {
        return new AchievementType();
    }

    /**
     * Create an instance of {@link Achievements }
     * 
     */
    public Achievements createAchievements() {
        return new Achievements();
    }

    /**
     * Create an instance of {@link Association }
     * 
     */
    public Association createAssociation() {
        return new Association();
    }

    /**
     * Create an instance of {@link FlexibleDatesType }
     * 
     */
    public FlexibleDatesType createFlexibleDatesType() {
        return new FlexibleDatesType();
    }

    /**
     * Create an instance of {@link AssociationType.Role }
     * 
     */
    public AssociationType.Role createAssociationTypeRole() {
        return new AssociationType.Role();
    }

    /**
     * Create an instance of {@link Associations }
     * 
     */
    public Associations createAssociations() {
        return new Associations();
    }

    /**
     * Create an instance of {@link DunsNumberDataType }
     * 
     */
    public DunsNumberDataType createDunsNumberDataType() {
        return new DunsNumberDataType();
    }

    /**
     * Create an instance of {@link EducationHistoryType }
     * 
     */
    public EducationHistoryType createEducationHistoryType() {
        return new EducationHistoryType();
    }

    /**
     * Create an instance of {@link EmploymentHistoryType }
     * 
     */
    public EmploymentHistoryType createEmploymentHistoryType() {
        return new EmploymentHistoryType();
    }

    /**
     * Create an instance of {@link TelcomNumberType }
     * 
     */
    public TelcomNumberType createTelcomNumberType() {
        return new TelcomNumberType();
    }

    /**
     * Create an instance of {@link InternetDomainNameType }
     * 
     */
    public InternetDomainNameType createInternetDomainNameType() {
        return new InternetDomainNameType();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link LicensesAndCertifications }
     * 
     */
    public LicensesAndCertifications createLicensesAndCertifications() {
        return new LicensesAndCertifications();
    }

    /**
     * Create an instance of {@link MobileTelcomNumberType }
     * 
     */
    public MobileTelcomNumberType createMobileTelcomNumberType() {
        return new MobileTelcomNumberType();
    }

    /**
     * Create an instance of {@link NonXMLResumeType }
     * 
     */
    public NonXMLResumeType createNonXMLResumeType() {
        return new NonXMLResumeType();
    }

    /**
     * Create an instance of {@link com.ufj.parser.model.sovren.NumericValue }
     * 
     */
    public com.ufj.parser.model.sovren.NumericValue createNumericValue() {
        return new com.ufj.parser.model.sovren.NumericValue();
    }

    /**
     * Create an instance of {@link PatentHistoryType }
     * 
     */
    public PatentHistoryType createPatentHistoryType() {
        return new PatentHistoryType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link References }
     * 
     */
    public References createReferences() {
        return new References();
    }

    /**
     * Create an instance of {@link Resume.UserArea }
     * 
     */
    public Resume.UserArea createResumeUserArea() {
        return new Resume.UserArea();
    }

    /**
     * Create an instance of {@link SecurityCredentials }
     * 
     */
    public SecurityCredentials createSecurityCredentials() {
        return new SecurityCredentials();
    }

    /**
     * Create an instance of {@link SpeakingEventType }
     * 
     */
    public SpeakingEventType createSpeakingEventType() {
        return new SpeakingEventType();
    }

    /**
     * Create an instance of {@link SpeakingEventsHistory }
     * 
     */
    public SpeakingEventsHistory createSpeakingEventsHistory() {
        return new SpeakingEventsHistory();
    }

    /**
     * Create an instance of {@link com.ufj.parser.model.sovren.StringValue }
     *
     */
    public com.ufj.parser.model.sovren.StringValue createStringValue() {
        return new com.ufj.parser.model.sovren.StringValue();
    }

    /**
     * Create an instance of {@link UserAreaType }
     * 
     */
    public UserAreaType createUserAreaType() {
        return new UserAreaType();
    }

    /**
     * Create an instance of {@link ArticleType }
     * 
     */
    public ArticleType createArticleType() {
        return new ArticleType();
    }

    /**
     * Create an instance of {@link BookType }
     * 
     */
    public BookType createBookType() {
        return new BookType();
    }

    /**
     * Create an instance of {@link ConferencePaperType }
     * 
     */
    public ConferencePaperType createConferencePaperType() {
        return new ConferencePaperType();
    }

    /**
     * Create an instance of {@link ContactMethodType }
     * 
     */
    public ContactMethodType createContactMethodType() {
        return new ContactMethodType();
    }

    /**
     * Create an instance of {@link DatesOfAttendanceType }
     * 
     */
    public DatesOfAttendanceType createDatesOfAttendanceType() {
        return new DatesOfAttendanceType();
    }

    /**
     * Create an instance of {@link DatesOfServiceType }
     * 
     */
    public DatesOfServiceType createDatesOfServiceType() {
        return new DatesOfServiceType();
    }

    /**
     * Create an instance of {@link DeprecatedDatesOfAttendanceType }
     * 
     */
    public DeprecatedDatesOfAttendanceType createDeprecatedDatesOfAttendanceType() {
        return new DeprecatedDatesOfAttendanceType();
    }

    /**
     * Create an instance of {@link DistributionType }
     * 
     */
    public DistributionType createDistributionType() {
        return new DistributionType();
    }

    /**
     * Create an instance of {@link EducationMeasureType }
     * 
     */
    public EducationMeasureType createEducationMeasureType() {
        return new EducationMeasureType();
    }

    /**
     * Create an instance of {@link EduMeasureType }
     * 
     */
    public EduMeasureType createEduMeasureType() {
        return new EduMeasureType();
    }

    /**
     * Create an instance of {@link EmpContactInfoType }
     * 
     */
    public EmpContactInfoType createEmpContactInfoType() {
        return new EmpContactInfoType();
    }

    /**
     * Create an instance of {@link EmploymentLocationSummaryType }
     * 
     */
    public EmploymentLocationSummaryType createEmploymentLocationSummaryType() {
        return new EmploymentLocationSummaryType();
    }

    /**
     * Create an instance of {@link EmploymentQuestionAnswerPairType }
     * 
     */
    public EmploymentQuestionAnswerPairType createEmploymentQuestionAnswerPairType() {
        return new EmploymentQuestionAnswerPairType();
    }

    /**
     * Create an instance of {@link IssuingAuthorityType }
     * 
     */
    public IssuingAuthorityType createIssuingAuthorityType() {
        return new IssuingAuthorityType();
    }

    /**
     * Create an instance of {@link JobLevelInfoType }
     * 
     */
    public JobLevelInfoType createJobLevelInfoType() {
        return new JobLevelInfoType();
    }

    /**
     * Create an instance of {@link MajorType }
     * 
     */
    public MajorType createMajorType() {
        return new MajorType();
    }

    /**
     * Create an instance of {@link MeasureValueType }
     * 
     */
    public MeasureValueType createMeasureValueType() {
        return new MeasureValueType();
    }

    /**
     * Create an instance of {@link MinorType }
     * 
     */
    public MinorType createMinorType() {
        return new MinorType();
    }

    /**
     * Create an instance of {@link OtherPublicationType }
     * 
     */
    public OtherPublicationType createOtherPublicationType() {
        return new OtherPublicationType();
    }

    /**
     * Create an instance of {@link PositionOrgInfoType }
     * 
     */
    public PositionOrgInfoType createPositionOrgInfoType() {
        return new PositionOrgInfoType();
    }

    /**
     * Create an instance of {@link PositionOrgNameType }
     * 
     */
    public PositionOrgNameType createPositionOrgNameType() {
        return new PositionOrgNameType();
    }

    /**
     * Create an instance of {@link ProfessionalAssociationType }
     * 
     */
    public ProfessionalAssociationType createProfessionalAssociationType() {
        return new ProfessionalAssociationType();
    }

    /**
     * Create an instance of {@link RankAchievedType }
     * 
     */
    public RankAchievedType createRankAchievedType() {
        return new RankAchievedType();
    }

    /**
     * Create an instance of {@link SchoolDataType }
     * 
     */
    public SchoolDataType createSchoolDataType() {
        return new SchoolDataType();
    }

    /**
     * Create an instance of {@link SEPContactInfoType }
     * 
     */
    public SEPContactInfoType createSEPContactInfoType() {
        return new SEPContactInfoType();
    }

    /**
     * Create an instance of {@link SourceTypeType }
     * 
     */
    public SourceTypeType createSourceTypeType() {
        return new SourceTypeType();
    }

    /**
     * Create an instance of {@link VerificationType.ContactInfo }
     * 
     */
    public VerificationType.ContactInfo createVerificationTypeContactInfo() {
        return new VerificationType.ContactInfo();
    }

    /**
     * Create an instance of {@link StaffingSupportingMaterialsType.AttachmentReference }
     * 
     */
    public StaffingSupportingMaterialsType.AttachmentReference createStaffingSupportingMaterialsTypeAttachmentReference() {
        return new StaffingSupportingMaterialsType.AttachmentReference();
    }

    /**
     * Create an instance of {@link SchoolOrInstitutionType.LocationSummary }
     * 
     */
    public SchoolOrInstitutionType.LocationSummary createSchoolOrInstitutionTypeLocationSummary() {
        return new SchoolOrInstitutionType.LocationSummary();
    }

    /**
     * Create an instance of {@link SchoolOrInstitutionType.OrganizationUnit }
     * 
     */
    public SchoolOrInstitutionType.OrganizationUnit createSchoolOrInstitutionTypeOrganizationUnit() {
        return new SchoolOrInstitutionType.OrganizationUnit();
    }

    /**
     * Create an instance of {@link SchoolOrInstitutionType.UserArea }
     * 
     */
    public SchoolOrInstitutionType.UserArea createSchoolOrInstitutionTypeUserArea() {
        return new SchoolOrInstitutionType.UserArea();
    }

    /**
     * Create an instance of {@link RatingType.NumericValue }
     * 
     */
    public RatingType.NumericValue createRatingTypeNumericValue() {
        return new RatingType.NumericValue();
    }

    /**
     * Create an instance of {@link RatingType.StringValue }
     * 
     */
    public RatingType.StringValue createRatingTypeStringValue() {
        return new RatingType.StringValue();
    }

    /**
     * Create an instance of {@link PositionOrgIndustryType.IndustryCode }
     * 
     */
    public PositionOrgIndustryType.IndustryCode createPositionOrgIndustryTypeIndustryCode() {
        return new PositionOrgIndustryType.IndustryCode();
    }

    /**
     * Create an instance of {@link PositionHistoryType.UserArea }
     * 
     */
    public PositionHistoryType.UserArea createPositionHistoryTypeUserArea() {
        return new PositionHistoryType.UserArea();
    }

    /**
     * Create an instance of {@link PositionCompensationType.StartingCompensation }
     * 
     */
    public PositionCompensationType.StartingCompensation createPositionCompensationTypeStartingCompensation() {
        return new PositionCompensationType.StartingCompensation();
    }

    /**
     * Create an instance of {@link PositionCompensationType.EndingCompensation }
     * 
     */
    public PositionCompensationType.EndingCompensation createPositionCompensationTypeEndingCompensation() {
        return new PositionCompensationType.EndingCompensation();
    }

    /**
     * Create an instance of {@link PositionCompensationType.OtherCompensation }
     * 
     */
    public PositionCompensationType.OtherCompensation createPositionCompensationTypeOtherCompensation() {
        return new PositionCompensationType.OtherCompensation();
    }

    /**
     * Create an instance of {@link PatentDescriptionType.Inventors }
     * 
     */
    public PatentDescriptionType.Inventors createPatentDescriptionTypeInventors() {
        return new PatentDescriptionType.Inventors();
    }

    /**
     * Create an instance of {@link PatentDescriptionType.PatentDetail.IssuingAuthority }
     * 
     */
    public PatentDescriptionType.PatentDetail.IssuingAuthority createPatentDescriptionTypePatentDetailIssuingAuthority() {
        return new PatentDescriptionType.PatentDetail.IssuingAuthority();
    }

    /**
     * Create an instance of {@link PatentDescriptionType.PatentDetail.PatentMilestone }
     * 
     */
    public PatentDescriptionType.PatentDetail.PatentMilestone createPatentDescriptionTypePatentDetailPatentMilestone() {
        return new PatentDescriptionType.PatentDetail.PatentMilestone();
    }

    /**
     * Create an instance of {@link BasicBibliographicRecordType.Name }
     * 
     */
    public BasicBibliographicRecordType.Name createBasicBibliographicRecordTypeName() {
        return new BasicBibliographicRecordType.Name();
    }

    /**
     * Create an instance of {@link PersonNameType.FamilyName }
     * 
     */
    public PersonNameType.FamilyName createPersonNameTypeFamilyName() {
        return new PersonNameType.FamilyName();
    }

    /**
     * Create an instance of {@link PersonNameType.Affix }
     * 
     */
    public PersonNameType.Affix createPersonNameTypeAffix() {
        return new PersonNameType.Affix();
    }

    /**
     * Create an instance of {@link PersonNameType.AlternateScript.FamilyName }
     * 
     */
    public PersonNameType.AlternateScript.FamilyName createPersonNameTypeAlternateScriptFamilyName() {
        return new PersonNameType.AlternateScript.FamilyName();
    }

    /**
     * Create an instance of {@link PersonNameType.AlternateScript.Affix }
     * 
     */
    public PersonNameType.AlternateScript.Affix createPersonNameTypeAlternateScriptAffix() {
        return new PersonNameType.AlternateScript.Affix();
    }

    /**
     * Create an instance of {@link OccupationalCategoryType.TaxonomyName }
     * 
     */
    public OccupationalCategoryType.TaxonomyName createOccupationalCategoryTypeTaxonomyName() {
        return new OccupationalCategoryType.TaxonomyName();
    }

    /**
     * Create an instance of {@link EmployerOrgDataType.PositionHistory }
     * 
     */
    public EmployerOrgDataType.PositionHistory createEmployerOrgDataTypePositionHistory() {
        return new EmployerOrgDataType.PositionHistory();
    }

    /**
     * Create an instance of {@link EmployerOrgDataType.UserArea }
     * 
     */
    public EmployerOrgDataType.UserArea createEmployerOrgDataTypeUserArea() {
        return new EmployerOrgDataType.UserArea();
    }

    /**
     * Create an instance of {@link EduDegreeType.DegreeName }
     * 
     */
    public EduDegreeType.DegreeName createEduDegreeTypeDegreeName() {
        return new EduDegreeType.DegreeName();
    }

    /**
     * Create an instance of {@link EduDegreeType.OtherHonors }
     * 
     */
    public EduDegreeType.OtherHonors createEduDegreeTypeOtherHonors() {
        return new EduDegreeType.OtherHonors();
    }

    /**
     * Create an instance of {@link EduDegreeType.UserArea }
     * 
     */
    public EduDegreeType.UserArea createEduDegreeTypeUserArea() {
        return new EduDegreeType.UserArea();
    }

    /**
     * Create an instance of {@link EducationalMeasureType.ClassRank }
     * 
     */
    public EducationalMeasureType.ClassRank createEducationalMeasureTypeClassRank() {
        return new EducationalMeasureType.ClassRank();
    }

    /**
     * Create an instance of {@link CopyrightType.CopyrightDates }
     * 
     */
    public CopyrightType.CopyrightDates createCopyrightTypeCopyrightDates() {
        return new CopyrightType.CopyrightDates();
    }

    /**
     * Create an instance of {@link AdditionalItemType.EffectiveDate }
     * 
     */
    public AdditionalItemType.EffectiveDate createAdditionalItemTypeEffectiveDate() {
        return new AdditionalItemType.EffectiveDate();
    }

    /**
     * Create an instance of {@link StructuredXMLResumeType.Qualifications }
     * 
     */
    public StructuredXMLResumeType.Qualifications createStructuredXMLResumeTypeQualifications() {
        return new StructuredXMLResumeType.Qualifications();
    }

    /**
     * Create an instance of {@link StructuredXMLResumeType.Languages }
     * 
     */
    public StructuredXMLResumeType.Languages createStructuredXMLResumeTypeLanguages() {
        return new StructuredXMLResumeType.Languages();
    }

    /**
     * Create an instance of {@link StructuredXMLResumeType.ResumeAdditionalItems }
     * 
     */
    public StructuredXMLResumeType.ResumeAdditionalItems createStructuredXMLResumeTypeResumeAdditionalItems() {
        return new StructuredXMLResumeType.ResumeAdditionalItems();
    }

    /**
     * Create an instance of {@link DistributionGuidelinesType.DistributeTo }
     * 
     */
    public DistributionGuidelinesType.DistributeTo createDistributionGuidelinesTypeDistributeTo() {
        return new DistributionGuidelinesType.DistributeTo();
    }

    /**
     * Create an instance of {@link PublicationHistoryType.FormattedPublicationDescription }
     * 
     */
    public PublicationHistoryType.FormattedPublicationDescription createPublicationHistoryTypeFormattedPublicationDescription() {
        return new PublicationHistoryType.FormattedPublicationDescription();
    }

    /**
     * Create an instance of {@link PostalAddressType.DeliveryAddress }
     * 
     */
    public PostalAddressType.DeliveryAddress createPostalAddressTypeDeliveryAddress() {
        return new PostalAddressType.DeliveryAddress();
    }

    /**
     * Create an instance of {@link PostalAddressType.Recipient }
     * 
     */
    public PostalAddressType.Recipient createPostalAddressTypeRecipient() {
        return new PostalAddressType.Recipient();
    }

    /**
     * Create an instance of {@link MilitaryHistoryType.ServiceDetail }
     * 
     */
    public MilitaryHistoryType.ServiceDetail createMilitaryHistoryTypeServiceDetail() {
        return new MilitaryHistoryType.ServiceDetail();
    }

    /**
     * Create an instance of {@link CredentialType.EffectiveDate }
     * 
     */
    public CredentialType.EffectiveDate createCredentialTypeEffectiveDate() {
        return new CredentialType.EffectiveDate();
    }

    /**
     * Create an instance of {@link CompetencyType.CompetencyId }
     * 
     */
    public CompetencyType.CompetencyId createCompetencyTypeCompetencyId() {
        return new CompetencyType.CompetencyId();
    }

    /**
     * Create an instance of {@link CompetencyType.TaxonomyId }
     * 
     */
    public CompetencyType.TaxonomyId createCompetencyTypeTaxonomyId() {
        return new CompetencyType.TaxonomyId();
    }

    /**
     * Create an instance of {@link CompetencyType.CompetencyWeight }
     * 
     */
    public CompetencyType.CompetencyWeight createCompetencyTypeCompetencyWeight() {
        return new CompetencyType.CompetencyWeight();
    }

    /**
     * Create an instance of {@link CompetencyType.CompetencyEvidence.EvidenceId }
     * 
     */
    public CompetencyType.CompetencyEvidence.EvidenceId createCompetencyTypeCompetencyEvidenceEvidenceId() {
        return new CompetencyType.CompetencyEvidence.EvidenceId();
    }

    /**
     * Create an instance of {@link EntityIdType.IdValue }
     * 
     */
    public EntityIdType.IdValue createEntityIdTypeIdValue() {
        return new EntityIdType.IdValue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AchievementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "Achievement")
    public JAXBElement<AchievementType> createAchievement(AchievementType value) {
        return new JAXBElement<AchievementType>(_Achievement_QNAME, AchievementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "AreaCityCode")
    public JAXBElement<String> createAreaCityCode(String value) {
        return new JAXBElement<String>(_AreaCityCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompetencyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "Competency")
    public JAXBElement<CompetencyType> createCompetency(CompetencyType value) {
        return new JAXBElement<CompetencyType>(_Competency_QNAME, CompetencyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "CountryCode")
    public JAXBElement<String> createCountryCode(String value) {
        return new JAXBElement<String>(_CountryCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "CurrencyCode")
    public JAXBElement<String> createCurrencyCode(String value) {
        return new JAXBElement<String>(_CurrencyCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DunsNumberDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "DunsNumber")
    public JAXBElement<DunsNumberDataType> createDunsNumber(DunsNumberDataType value) {
        return new JAXBElement<DunsNumberDataType>(_DunsNumber_QNAME, DunsNumberDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EducationHistoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "EducationHistory")
    public JAXBElement<EducationHistoryType> createEducationHistory(EducationHistoryType value) {
        return new JAXBElement<EducationHistoryType>(_EducationHistory_QNAME, EducationHistoryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmploymentHistoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "EmploymentHistory")
    public JAXBElement<EmploymentHistoryType> createEmploymentHistory(EmploymentHistoryType value) {
        return new JAXBElement<EmploymentHistoryType>(_EmploymentHistory_QNAME, EmploymentHistoryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "Extension")
    public JAXBElement<String> createExtension(String value) {
        return new JAXBElement<String>(_Extension_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelcomNumberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "Fax")
    public JAXBElement<TelcomNumberType> createFax(TelcomNumberType value) {
        return new JAXBElement<TelcomNumberType>(_Fax_QNAME, TelcomNumberType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "FormattedNumber")
    public JAXBElement<String> createFormattedNumber(String value) {
        return new JAXBElement<String>(_FormattedNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "GenderCode")
    public JAXBElement<BigInteger> createGenderCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_GenderCode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "InternationalCountryCode")
    public JAXBElement<String> createInternationalCountryCode(String value) {
        return new JAXBElement<String>(_InternationalCountryCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternetDomainNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "InternetDomainName")
    public JAXBElement<InternetDomainNameType> createInternetDomainName(InternetDomainNameType value) {
        return new JAXBElement<InternetDomainNameType>(_InternetDomainName_QNAME, InternetDomainNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "InternetEmailAddress")
    public JAXBElement<String> createInternetEmailAddress(String value) {
        return new JAXBElement<String>(_InternetEmailAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "InternetWebAddress")
    public JAXBElement<String> createInternetWebAddress(String value) {
        return new JAXBElement<String>(_InternetWebAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "LanguageCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLanguageCode(String value) {
        return new JAXBElement<String>(_LanguageCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CredentialType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "LicenseOrCertification")
    public JAXBElement<CredentialType> createLicenseOrCertification(CredentialType value) {
        return new JAXBElement<CredentialType>(_LicenseOrCertification_QNAME, CredentialType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "Location")
    public JAXBElement<String> createLocation(String value) {
        return new JAXBElement<String>(_Location_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MilitaryHistoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "MilitaryHistory")
    public JAXBElement<MilitaryHistoryType> createMilitaryHistory(MilitaryHistoryType value) {
        return new JAXBElement<MilitaryHistoryType>(_MilitaryHistory_QNAME, MilitaryHistoryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MobileTelcomNumberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "Mobile")
    public JAXBElement<MobileTelcomNumberType> createMobile(MobileTelcomNumberType value) {
        return new JAXBElement<MobileTelcomNumberType>(_Mobile_QNAME, MobileTelcomNumberType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "NationalNumber")
    public JAXBElement<String> createNationalNumber(String value) {
        return new JAXBElement<String>(_NationalNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonXMLResumeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "NonXMLResume")
    public JAXBElement<NonXMLResumeType> createNonXMLResume(NonXMLResumeType value) {
        return new JAXBElement<NonXMLResumeType>(_NonXMLResume_QNAME, NonXMLResumeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelcomNumberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "Pager")
    public JAXBElement<TelcomNumberType> createPager(TelcomNumberType value) {
        return new JAXBElement<TelcomNumberType>(_Pager_QNAME, TelcomNumberType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatentHistoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "PatentHistory")
    public JAXBElement<PatentHistoryType> createPatentHistory(PatentHistoryType value) {
        return new JAXBElement<PatentHistoryType>(_PatentHistory_QNAME, PatentHistoryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "PersonName")
    public JAXBElement<PersonNameType> createPersonName(PersonNameType value) {
        return new JAXBElement<PersonNameType>(_PersonName_QNAME, PersonNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostalAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "PostalAddress")
    public JAXBElement<PostalAddressType> createPostalAddress(PostalAddressType value) {
        return new JAXBElement<PostalAddressType>(_PostalAddress_QNAME, PostalAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublicationHistoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "PublicationHistory")
    public JAXBElement<PublicationHistoryType> createPublicationHistory(PublicationHistoryType value) {
        return new JAXBElement<PublicationHistoryType>(_PublicationHistory_QNAME, PublicationHistoryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "Reference")
    public JAXBElement<ReferenceType> createReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_Reference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredXMLResumeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "StructuredXMLResume")
    public JAXBElement<StructuredXMLResumeType> createStructuredXMLResume(StructuredXMLResumeType value) {
        return new JAXBElement<StructuredXMLResumeType>(_StructuredXMLResume_QNAME, StructuredXMLResumeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdditionalItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "ResumeAdditionalItem")
    public JAXBElement<AdditionalItemType> createResumeAdditionalItem(AdditionalItemType value) {
        return new JAXBElement<AdditionalItemType>(_ResumeAdditionalItem_QNAME, AdditionalItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CredentialType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "SecurityCredential")
    public JAXBElement<CredentialType> createSecurityCredential(CredentialType value) {
        return new JAXBElement<CredentialType>(_SecurityCredential_QNAME, CredentialType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpeakingEventType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "SpeakingEvent")
    public JAXBElement<SpeakingEventType> createSpeakingEvent(SpeakingEventType value) {
        return new JAXBElement<SpeakingEventType>(_SpeakingEvent_QNAME, SpeakingEventType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "SubscriberNumber")
    public JAXBElement<String> createSubscriberNumber(String value) {
        return new JAXBElement<String>(_SubscriberNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "SupportingInformation")
    public JAXBElement<String> createSupportingInformation(String value) {
        return new JAXBElement<String>(_SupportingInformation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelcomNumberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "Telephone")
    public JAXBElement<TelcomNumberType> createTelephone(TelcomNumberType value) {
        return new JAXBElement<TelcomNumberType>(_Telephone_QNAME, TelcomNumberType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelcomNumberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "TTYTDD")
    public JAXBElement<TelcomNumberType> createTTYTDD(TelcomNumberType value) {
        return new JAXBElement<TelcomNumberType>(_TTYTDD_QNAME, TelcomNumberType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "Use")
    public JAXBElement<String> createUse(String value) {
        return new JAXBElement<String>(_Use_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserAreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "UserArea")
    public JAXBElement<UserAreaType> createUserArea(UserAreaType value) {
        return new JAXBElement<UserAreaType>(_UserArea_QNAME, UserAreaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "WhenAvailable")
    public JAXBElement<String> createWhenAvailable(String value) {
        return new JAXBElement<String>(_WhenAvailable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlexibleDatesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "StartDate", scope = DeprecatedDatesOfAttendanceType.class)
    public JAXBElement<FlexibleDatesType> createDeprecatedDatesOfAttendanceTypeStartDate(FlexibleDatesType value) {
        return new JAXBElement<FlexibleDatesType>(_DeprecatedDatesOfAttendanceTypeStartDate_QNAME, FlexibleDatesType.class, DeprecatedDatesOfAttendanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlexibleDatesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ns.hr-xml.org/2006-02-28", name = "EndDate", scope = DeprecatedDatesOfAttendanceType.class)
    public JAXBElement<FlexibleDatesType> createDeprecatedDatesOfAttendanceTypeEndDate(FlexibleDatesType value) {
        return new JAXBElement<FlexibleDatesType>(_DeprecatedDatesOfAttendanceTypeEndDate_QNAME, FlexibleDatesType.class, DeprecatedDatesOfAttendanceType.class, value);
    }

}
