//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for positionTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="positionTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="directHire"/&gt;
 *     &lt;enumeration value="contract"/&gt;
 *     &lt;enumeration value="temp"/&gt;
 *     &lt;enumeration value="contractToHire"/&gt;
 *     &lt;enumeration value="tempToHire"/&gt;
 *     &lt;enumeration value="volunteer"/&gt;
 *     &lt;enumeration value="internship"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "positionTypes")
@XmlEnum
public enum PositionTypes {

    @XmlEnumValue("directHire")
    DIRECT_HIRE("directHire"),
    @XmlEnumValue("contract")
    CONTRACT("contract"),
    @XmlEnumValue("temp")
    TEMP("temp"),
    @XmlEnumValue("contractToHire")
    CONTRACT_TO_HIRE("contractToHire"),
    @XmlEnumValue("tempToHire")
    TEMP_TO_HIRE("tempToHire"),
    @XmlEnumValue("volunteer")
    VOLUNTEER("volunteer"),
    @XmlEnumValue("internship")
    INTERNSHIP("internship");
    private final String value;

    PositionTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PositionTypes fromValue(String v) {
        for (PositionTypes c: PositionTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
