//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PublicationOtherTypeTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PublicationOtherTypeTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Thesis"/&gt;
 *     &lt;enumeration value="Whitepaper"/&gt;
 *     &lt;enumeration value="Report"/&gt;
 *     &lt;enumeration value="TechnicalDocumentation"/&gt;
 *     &lt;enumeration value="Study"/&gt;
 *     &lt;enumeration value="Manual"/&gt;
 *     &lt;enumeration value="ResearchPaper"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PublicationOtherTypeTypes")
@XmlEnum
public enum PublicationOtherTypeTypes {

    @XmlEnumValue("Thesis")
    THESIS("Thesis"),
    @XmlEnumValue("Whitepaper")
    WHITEPAPER("Whitepaper"),
    @XmlEnumValue("Report")
    REPORT("Report"),
    @XmlEnumValue("TechnicalDocumentation")
    TECHNICAL_DOCUMENTATION("TechnicalDocumentation"),
    @XmlEnumValue("Study")
    STUDY("Study"),
    @XmlEnumValue("Manual")
    MANUAL("Manual"),
    @XmlEnumValue("ResearchPaper")
    RESEARCH_PAPER("ResearchPaper");
    private final String value;

    PublicationOtherTypeTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PublicationOtherTypeTypes fromValue(String v) {
        for (PublicationOtherTypeTypes c: PublicationOtherTypeTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
