//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import com.sovren.hr_xml._2006_02_28.SchoolOrInstitutionTypeUserArea;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for SchoolOrInstitutionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SchoolOrInstitutionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SchoolName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="School" type="{http://ns.hr-xml.org/2006-02-28}SchoolDataType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="LocationSummary" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Municipality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element ref="{http://ns.hr-xml.org/2006-02-28}CountryCode" minOccurs="0"/&gt;
 *                   &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element ref="{http://ns.hr-xml.org/2006-02-28}PostalAddress" minOccurs="0"/&gt;
 *         &lt;element name="OrganizationUnit" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="organizationType" use="required" type="{http://ns.hr-xml.org/2006-02-28}OrgTypeStringExtensionType" /&gt;
 *                 &lt;attribute name="attendanceStatus"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;enumeration value="current"/&gt;
 *                       &lt;enumeration value="prior"/&gt;
 *                       &lt;enumeration value="unknown"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Degree" type="{http://ns.hr-xml.org/2006-02-28}EduDegreeType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Major" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Minor" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Measure" type="{http://ns.hr-xml.org/2006-02-28}EduMeasureType" minOccurs="0"/&gt;
 *         &lt;element name="DatesOfAttendance" type="{http://ns.hr-xml.org/2006-02-28}DeprecatedDatesOfAttendanceType" minOccurs="0"/&gt;
 *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UserArea" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                   &lt;element ref="{http://sovren.com/hr-xml/2006-02-28}SchoolOrInstitutionTypeUserArea" minOccurs="0"/&gt;
 *                 &lt;/all&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="schoolType" use="required" type="{http://ns.hr-xml.org/2006-02-28}SchoolTypeStringExtensionType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SchoolOrInstitutionType", propOrder = {
    "schoolName",
    "school",
    "locationSummary",
    "postalAddress",
    "organizationUnit",
    "degree",
    "major",
    "minor",
    "measure",
    "datesOfAttendance",
    "comments",
    "userArea"
})
public class SchoolOrInstitutionType {

    @XmlElement(name = "SchoolName")
    protected String schoolName;
    @XmlElement(name = "School")
    protected List<SchoolDataType> school;
    @XmlElement(name = "LocationSummary")
    protected SchoolOrInstitutionType.LocationSummary locationSummary;
    @XmlElement(name = "PostalAddress")
    protected PostalAddressType postalAddress;
    @XmlElement(name = "OrganizationUnit")
    protected List<OrganizationUnit> organizationUnit;
    @XmlElement(name = "Degree")
    protected List<EduDegreeType> degree;
    @XmlElement(name = "Major")
    protected List<String> major;
    @XmlElement(name = "Minor")
    protected List<String> minor;
    @XmlElement(name = "Measure")
    protected EduMeasureType measure;
    @XmlElement(name = "DatesOfAttendance")
    protected DeprecatedDatesOfAttendanceType datesOfAttendance;
    @XmlElement(name = "Comments")
    protected String comments;
    @XmlElement(name = "UserArea")
    protected SchoolOrInstitutionType.UserArea userArea;
    @XmlAttribute(name = "schoolType", required = true)
    protected String schoolType;

    /**
     * Gets the value of the schoolName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * Sets the value of the schoolName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSchoolName(String value) {
        this.schoolName = value;
    }

    /**
     * Gets the value of the school property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the school property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSchool().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SchoolDataType }
     *
     *
     */
    public List<SchoolDataType> getSchool() {
        if (school == null) {
            school = new ArrayList<SchoolDataType>();
        }
        return this.school;
    }

    /**
     * Gets the value of the locationSummary property.
     *
     * @return
     *     possible object is
     *     {@link SchoolOrInstitutionType.LocationSummary }
     *
     */
    public SchoolOrInstitutionType.LocationSummary getLocationSummary() {
        return locationSummary;
    }

    /**
     * Sets the value of the locationSummary property.
     *
     * @param value
     *     allowed object is
     *     {@link SchoolOrInstitutionType.LocationSummary }
     *
     */
    public void setLocationSummary(SchoolOrInstitutionType.LocationSummary value) {
        this.locationSummary = value;
    }

    /**
     * Gets the value of the postalAddress property.
     *
     * @return
     *     possible object is
     *     {@link PostalAddressType }
     *
     */
    public PostalAddressType getPostalAddress() {
        return postalAddress;
    }

    /**
     * Sets the value of the postalAddress property.
     *
     * @param value
     *     allowed object is
     *     {@link PostalAddressType }
     *
     */
    public void setPostalAddress(PostalAddressType value) {
        this.postalAddress = value;
    }

    /**
     * Gets the value of the organizationUnit property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organizationUnit property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganizationUnit().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SchoolOrInstitutionType.OrganizationUnit }
     *
     *
     */
    public List<OrganizationUnit> getOrganizationUnit() {
        if (organizationUnit == null) {
            organizationUnit = new ArrayList<OrganizationUnit>();
        }
        return this.organizationUnit;
    }

    /**
     * Gets the value of the degree property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the degree property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDegree().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EduDegreeType }
     *
     *
     */
    public List<EduDegreeType> getDegree() {
        if (degree == null) {
            degree = new ArrayList<EduDegreeType>();
        }
        return this.degree;
    }

    /**
     * Gets the value of the major property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the major property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMajor().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getMajor() {
        if (major == null) {
            major = new ArrayList<String>();
        }
        return this.major;
    }

    /**
     * Gets the value of the minor property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the minor property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMinor().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getMinor() {
        if (minor == null) {
            minor = new ArrayList<String>();
        }
        return this.minor;
    }

    /**
     * Gets the value of the measure property.
     *
     * @return
     *     possible object is
     *     {@link EduMeasureType }
     *
     */
    public EduMeasureType getMeasure() {
        return measure;
    }

    /**
     * Sets the value of the measure property.
     *
     * @param value
     *     allowed object is
     *     {@link EduMeasureType }
     *
     */
    public void setMeasure(EduMeasureType value) {
        this.measure = value;
    }

    /**
     * Gets the value of the datesOfAttendance property.
     *
     * @return
     *     possible object is
     *     {@link DeprecatedDatesOfAttendanceType }
     *
     */
    public DeprecatedDatesOfAttendanceType getDatesOfAttendance() {
        return datesOfAttendance;
    }

    /**
     * Sets the value of the datesOfAttendance property.
     *
     * @param value
     *     allowed object is
     *     {@link DeprecatedDatesOfAttendanceType }
     *
     */
    public void setDatesOfAttendance(DeprecatedDatesOfAttendanceType value) {
        this.datesOfAttendance = value;
    }

    /**
     * Gets the value of the comments property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the userArea property.
     *
     * @return
     *     possible object is
     *     {@link SchoolOrInstitutionType.UserArea }
     *
     */
    public SchoolOrInstitutionType.UserArea getUserArea() {
        return userArea;
    }

    /**
     * Sets the value of the userArea property.
     *
     * @param value
     *     allowed object is
     *     {@link SchoolOrInstitutionType.UserArea }
     *
     */
    public void setUserArea(SchoolOrInstitutionType.UserArea value) {
        this.userArea = value;
    }

    /**
     * Gets the value of the schoolType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchoolType() {
        return schoolType;
    }

    /**
     * Sets the value of the schoolType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchoolType(String value) {
        this.schoolType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Municipality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element ref="{http://ns.hr-xml.org/2006-02-28}CountryCode" minOccurs="0"/&gt;
     *         &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "municipality",
        "region",
        "countryCode",
        "postalCode"
    })
    public static class LocationSummary {

        @XmlElement(name = "Municipality")
        protected String municipality;
        @XmlElement(name = "Region")
        protected List<String> region;
        @XmlElement(name = "CountryCode")
        protected String countryCode;
        @XmlElement(name = "PostalCode")
        protected String postalCode;

        /**
         * Gets the value of the municipality property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMunicipality() {
            return municipality;
        }

        /**
         * Sets the value of the municipality property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMunicipality(String value) {
            this.municipality = value;
        }

        /**
         * Gets the value of the region property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the region property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRegion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getRegion() {
            if (region == null) {
                region = new ArrayList<String>();
            }
            return this.region;
        }

        /**
         * Gets the value of the countryCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountryCode() {
            return countryCode;
        }

        /**
         * Sets the value of the countryCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountryCode(String value) {
            this.countryCode = value;
        }

        /**
         * Gets the value of the postalCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPostalCode() {
            return postalCode;
        }

        /**
         * Sets the value of the postalCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPostalCode(String value) {
            this.postalCode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="organizationType" use="required" type="{http://ns.hr-xml.org/2006-02-28}OrgTypeStringExtensionType" /&gt;
     *       &lt;attribute name="attendanceStatus"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;enumeration value="current"/&gt;
     *             &lt;enumeration value="prior"/&gt;
     *             &lt;enumeration value="unknown"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class OrganizationUnit {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "organizationType", required = true)
        protected String organizationType;
        @XmlAttribute(name = "attendanceStatus")
        protected String attendanceStatus;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the organizationType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrganizationType() {
            return organizationType;
        }

        /**
         * Sets the value of the organizationType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrganizationType(String value) {
            this.organizationType = value;
        }

        /**
         * Gets the value of the attendanceStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttendanceStatus() {
            return attendanceStatus;
        }

        /**
         * Sets the value of the attendanceStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttendanceStatus(String value) {
            this.attendanceStatus = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *         &lt;element ref="{http://sovren.com/hr-xml/2006-02-28}SchoolOrInstitutionTypeUserArea" minOccurs="0"/&gt;
     *       &lt;/all&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class UserArea {

        @XmlElement(name = "SchoolOrInstitutionTypeUserArea", namespace = "http://sovren.com/hr-xml/2006-02-28")
        protected SchoolOrInstitutionTypeUserArea schoolOrInstitutionTypeUserArea;

        /**
         * Gets the value of the schoolOrInstitutionTypeUserArea property.
         * 
         * @return
         *     possible object is
         *     {@link SchoolOrInstitutionTypeUserArea }
         *     
         */
        public SchoolOrInstitutionTypeUserArea getSchoolOrInstitutionTypeUserArea() {
            return schoolOrInstitutionTypeUserArea;
        }

        /**
         * Sets the value of the schoolOrInstitutionTypeUserArea property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchoolOrInstitutionTypeUserArea }
         *     
         */
        public void setSchoolOrInstitutionTypeUserArea(SchoolOrInstitutionTypeUserArea value) {
            this.schoolOrInstitutionTypeUserArea = value;
        }

    }

}
