//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.ufj.parser.model.sovren;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SourceEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SourceEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Job Board"/&gt;
 *     &lt;enumeration value="Staffing Agency"/&gt;
 *     &lt;enumeration value="Intermediary"/&gt;
 *     &lt;enumeration value="Referrer"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SourceEnumType")
@XmlEnum
public enum SourceEnumType {

    @XmlEnumValue("Job Board")
    JOB_BOARD("Job Board"),
    @XmlEnumValue("Staffing Agency")
    STAFFING_AGENCY("Staffing Agency"),
    @XmlEnumValue("Intermediary")
    INTERMEDIARY("Intermediary"),
    @XmlEnumValue("Referrer")
    REFERRER("Referrer");
    private final String value;

    SourceEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SourceEnumType fromValue(String v) {
        for (SourceEnumType c: SourceEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
