//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.sovren.hr_xml._2006_02_28;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for BestFitTaxonomyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BestFitTaxonomyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BestFitTaxonomy" type="{http://sovren.com/hr-xml/2006-02-28}BestFitTaxonomyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="rootId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="weight" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="percentOfOverall" use="required" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="percentOfParent" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BestFitTaxonomyType", propOrder = {
    "bestFitTaxonomy"
})
public class BestFitTaxonomyType {

    @XmlElement(name = "BestFitTaxonomy")
    protected List<BestFitTaxonomyType> bestFitTaxonomy;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "rootId", required = true)
    protected String rootId;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "weight")
    protected Double weight;
    @XmlAttribute(name = "percentOfOverall", required = true)
    protected double percentOfOverall;
    @XmlAttribute(name = "percentOfParent")
    protected Double percentOfParent;

    /**
     * Gets the value of the bestFitTaxonomy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bestFitTaxonomy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBestFitTaxonomy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BestFitTaxonomyType }
     * 
     * 
     */
    public List<BestFitTaxonomyType> getBestFitTaxonomy() {
        if (bestFitTaxonomy == null) {
            bestFitTaxonomy = new ArrayList<BestFitTaxonomyType>();
        }
        return this.bestFitTaxonomy;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the rootId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootId() {
        return rootId;
    }

    /**
     * Sets the value of the rootId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootId(String value) {
        this.rootId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWeight(Double value) {
        this.weight = value;
    }

    /**
     * Gets the value of the percentOfOverall property.
     * 
     */
    public double getPercentOfOverall() {
        return percentOfOverall;
    }

    /**
     * Sets the value of the percentOfOverall property.
     * 
     */
    public void setPercentOfOverall(double value) {
        this.percentOfOverall = value;
    }

    /**
     * Gets the value of the percentOfParent property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPercentOfParent() {
        return percentOfParent;
    }

    /**
     * Sets the value of the percentOfParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPercentOfParent(Double value) {
        this.percentOfParent = value;
    }

}
