//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.sovren.hr_xml._2006_02_28;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MaritalStatusEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MaritalStatusEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Married"/&gt;
 *     &lt;enumeration value="Single"/&gt;
 *     &lt;enumeration value="Divorced"/&gt;
 *     &lt;enumeration value="Separated"/&gt;
 *     &lt;enumeration value="CivilUnion"/&gt;
 *     &lt;enumeration value="Cohabitating"/&gt;
 *     &lt;enumeration value="Unknown"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MaritalStatusEnum")
@XmlEnum
public enum MaritalStatusEnum {

    @XmlEnumValue("Married")
    MARRIED("Married"),
    @XmlEnumValue("Single")
    SINGLE("Single"),
    @XmlEnumValue("Divorced")
    DIVORCED("Divorced"),
    @XmlEnumValue("Separated")
    SEPARATED("Separated"),
    @XmlEnumValue("CivilUnion")
    CIVIL_UNION("CivilUnion"),
    @XmlEnumValue("Cohabitating")
    COHABITATING("Cohabitating"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    MaritalStatusEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MaritalStatusEnum fromValue(String v) {
        for (MaritalStatusEnum c: MaritalStatusEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
