//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:50:38 PM EDT 
//


package com.sovren.hr_xml._2006_02_28;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrainingHistoryTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TrainingHistoryTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Unknown"/&gt;
 *     &lt;enumeration value="Professional"/&gt;
 *     &lt;enumeration value="Vocational"/&gt;
 *     &lt;enumeration value="Personal"/&gt;
 *     &lt;enumeration value="LowerCraft"/&gt;
 *     &lt;enumeration value="MiddleCraft"/&gt;
 *     &lt;enumeration value="HigherCraft"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TrainingHistoryTypeEnum")
@XmlEnum
public enum TrainingHistoryTypeEnum {

    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown"),
    @XmlEnumValue("Professional")
    PROFESSIONAL("Professional"),
    @XmlEnumValue("Vocational")
    VOCATIONAL("Vocational"),
    @XmlEnumValue("Personal")
    PERSONAL("Personal"),
    @XmlEnumValue("LowerCraft")
    LOWER_CRAFT("LowerCraft"),
    @XmlEnumValue("MiddleCraft")
    MIDDLE_CRAFT("MiddleCraft"),
    @XmlEnumValue("HigherCraft")
    HIGHER_CRAFT("HigherCraft");
    private final String value;

    TrainingHistoryTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TrainingHistoryTypeEnum fromValue(String v) {
        for (TrainingHistoryTypeEnum c: TrainingHistoryTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
